### ISSUE TITLE
Weird undocumented behavior of the "%shared_ptr" for the C++ templates

### ISSUE THREAD

**Issue by luav** [swig/swig#1049]
Documentation for the [%shared_ptr](http://swig.org/Doc3.0/Library.html#Library_std_shared_ptr) should be extended covering interaction with C++ templates.

If `Hierarchy` is a template then usage of `%shared_ptr(Hierarchy);` yields the following error:
```c++
error: type/value mismatch at argument 1 in template parameter list for 'template<class _Tp> class std::shared_ptr'
   std::shared_ptr< Hierarchy > tempshared1 ;
                              ^
compilation terminated due to -Wfatal-errors.
```
If `SHierarchy` is one of the instantiations of the `Hierarchy`, for example:
```c++
%template(SHierarchy) Hierarchy<SomeType>;
%template(AHierarchy) Hierarchy<AnotherType>;
```
then `%shared_ptr(SHierarchy);` results in the transparent shared_ptr also for `AHierarchy` (**unexpected**) and all other classes that are instances of the `Hierarchy` template, which should be documented and *should yield some warning* on the wrapper generation.

In the end, the right solution, which is **[not documented](http://swig.org/Doc3.0/Library.html#Library_std_shared_ptr)**:
```c++
%shared_ptr(Hierarchy<>);
```

**Comment by ojwb** [comment]
Please can you submit a patch to improve the documentation?

**Comment by luav** [comment]
The pull request for the documentation (manual) update has been performed.  
Still, it would be nice to *yield some warning on the wrapper generation* if the template specialization is used inside the `%shared_ptr` declaration, or to prevent such declarations at all.

**Comment by wsfulton** [comment]
I just found a way to reproduce the problem. A slight tweak to the newly documented code to use template default arguments is:
```c++
// number.h
#include <memory>

template<int N=42> struct Number {
  int num;
  Number() : num(N) {}
  static std::shared_ptr<Number<N>> make() { return std::make_shared<Number<N>>(); }
};
```
```swig
%include <std_shared_ptr.i>

%shared_ptr(Number<10>);
%shared_ptr(Number<>);

%{
  #include "number.h"
%}
%include "number.h"

%template(Number10) Number<10>;
%template(Number42) Number<>;
```
A Java type wrapper class `SWIGTYPE_p_std__shared_ptrT_NumberT_42_t_t` is generated instead of `Number42` which is indicative of a type lookup problem in SWIG. I can't reproduce your ` error: type/value mismatch` error originally provided though.

**Comment by luav** [comment]
The original issue is not reproduced on several simple examples, but reproduced in my project *permanently*. In the latest SWIG it has distinct error message.

Initially I tried the `%shared_ptr` instantiation for the template name without the parameters and `<>` brackets empirically trying to make it work without the respective documentation available.

The compilation is fine for:
```c++
%shared_ptr(Graph<>);
%shared_ptr(Nodes<>);
%shared_ptr(RawMembership<>);  // ! Has the same effect as %shared_ptr(SRawMembership)
```
But for the `%shared_ptr(Graph);` or `%shared_ptr(RawMembership);` (the template brackets are absent) respectively:
```sh
swig/wraps/daoc_python2.cxx:21513:22: error: ‘smartarg1’ was not declared in this scope
   (void)arg1; delete smartarg1;
                      ^
compilation terminated due to -Wfatal-errors.
Makefile:507: recipe for target 'obj/Release/python2/swig/wraps/daoc_python2.o' failed
make: *** [obj/Release/python2/swig/wraps/daoc_python2.o] Error 1
```
and
```sh
swig/wraps/daoc_python2.cxx:28046:10: note: in expansion of macro ‘SWIG_ConvertPtr’
   res1 = SWIG_ConvertPtr(swig_obj[0], &argp1,SWIGTYPE_p_daoc__RawMembershipT_s
          ^
swig/wraps/daoc_python2.cxx:28051:22: error: ‘smartarg1’ was not declared in this scope
   (void)arg1; delete smartarg1;
                      ^
compilation terminated due to -Wfatal-errors.
Makefile:507: recipe for target 'obj/Release/python2/swig/wraps/daoc_python2.o' failed
make: *** [obj/Release/python2/swig/wraps/daoc_python2.o] Error 1
```
But considering that such `%shared_ptr` call for the template is incorrect, it is not so important what exactly the error message is.

Declarations of the instantiated templates:
```c++
template <typename LinksT>
struct RawMembership {
	Clusters<LinksT>  clusters;
	NodesShares<LinksT>  ndshares;

	RawMembership(): clusters(), ndshares()  {}

	RawMembership(const RawMembership&)=delete;
	RawMembership(RawMembership&&)=default;

	RawMembership& operator=(const RawMembership&)=delete;
	RawMembership& operator=(RawMembership&&)=default;
};

template <bool LINKS_WEIGHTED=true>
class Graph {
	// Huge
	...
public:
	Graph(const Graph&)=delete;
	Graph(Graph&&)=default;

	Graph& operator=(const Graph&)=delete;
	Graph& operator=(Graph&&)=default;
};
```

**Comment by luav** [comment]
As for how I made the conclusion that only the single `%shared_ptr(Hierarchy<>);` should be used then it is related to the multiple issues in the begin of August related to templates, shared_ptrs and namespaces, many of which has been fixed withing the last month.  
For example, shared_ptr (both transparent and non-transparent, i.e. without `%shared_ptr`) can be returned now from the function, but a month ago it caused the compilation error:
```sh
$ g++ -std=c++14 -fPIC -Wfatal-errors -c ./clvec_wrap.cxx -I/usr/include/python2.7 && g++ -shared clvec_wrap.o -o _clvec.so
./clvec_wrap.cxx: In function ‘PyObject* _wrap_fsh(PyObject*, PyObject*)’:
./clvec_wrap.cxx:8183:97: error: could not convert ‘result’ from ‘SwigValueWrapper<std::shared_ptr<ShType> >’ to ‘bool’
 <  ShType > *smartresult = result ? new std::shared_ptr<  ShType >(result) : 0;
```
for the wrapper:
```c++                          
SWIGINTERN PyObject *_wrap_fsh(PyObject *SWIGUNUSEDPARM(self), PyObject *args) {
  PyObject *resultobj = 0;
  SwigValueWrapper< shared_ptr< ShType > > result;
  
  if (!PyArg_ParseTuple(args,(char *)":fsh")) SWIG_fail;
  result = fsh();
  {
    std::shared_ptr<  ShType > *smartresult = result ? new std::shared_ptr<  ShType >(result) : 0;				// <<< The compilation error was here
    resultobj = SWIG_NewPointerObj(SWIG_as_voidptr(smartresult), SWIGTYPE_p_std__shared_ptrT_ShType_t, SWIG_POINTER_OWN);
  }
  return resultobj;
fail:
  return NULL;
}                                 
```

It seems, the transparent `%shared_ptr` did not work actually for my case, I did not see any difference in declaring them for a single instantiation or for all instantiations, but at least they compiled with the declaration  `%shared_ptr(TplName<>);`. So, I assumed that it is how they should be declared.

**Comment by ojwb** [comment]
> A Java type wrapper class `SWIGTYPE_p_std__shared_ptrT_NumberT_42_t_t` is generated instead of `Number42` which is indicative of a type lookup problem in SWIG. I can't reproduce your ` error: type/value mismatch` error originally provided though.

Retesting wsfulton's reproducer with current git master I get *BOTH* `SWIGTYPE_p_std__shared_ptrT_NumberT_42_t_t.java` and `Number42.java`, which sounds like it's a change from before, but this still isn't working as it should.  I also get both with SWIG 4.1.0.
