### ISSUE TITLE
Enums with hex values parsed incorrectly for R

### ISSUE THREAD

**Issue by davidcreasy** [swig/swig#1116]
If I specify a value for enums using 'hex', then the enumerations all have a value of 0.
The same file works OK with Perl, Java, C# and Python, so I think it's just a bug for R?
Simple example:

// enums.h
class testEnum {
    public:
        enum SHAPES {
          SQUARE,
          TRIANGLE,
          RECTANGLE
        };
        enum COLOURS {
          RED   = 0x00FF0000,
          GREEN = 0x0000FF00,
          BLUE  = 0x000000FF
        };
        enum NUMBERS {
            ONE = 1,
            TWO = 2,
            THREE = 3
        }
        testEnum(bool notEmpty) { 
        }
    private:    
};

And a standard .i file:
/* File : enums.i */
%module enums

%{
#include "\tmp\enums.h"
%}

/* Let's just grab the original header file here */
%include "\tmp\enums.h"

SWIG'd with: 
swig.exe  -c++ -r  enums.i

Produces this in the .R file:
defineEnumeration('_testEnum__SHAPES',
                    .values = c(
                        'SQUARE' = 0, 
                        'TRIANGLE' = 1, 
                        'RECTANGLE' = 2
))
defineEnumeration('_testEnum__COLOURS',
                    .values = c(
                        'RED' = 0, 
                        'GREEN' = 0, 
                        'BLUE' = 0
))
defineEnumeration('_testEnum__NUMBERS',
                    .values = c(
                        'ONE' = 1, 
                        'TWO' = 2, 
                        'THREE' = 3
))

**Comment by ojwb** [comment]
It is indeed R-specific.  Interestingly your example actually seems to work on Linux, presumably due to differences in `sscanf`'s handling of `%lf`.  However, the handling here is buggy in several ways.

In `Sources/Modules/r.cxx` this is the code:

```
  Printv(scode, "defineEnumeration('", mangled_tdname, "'",
         ",\n",  tab8, tab8, tab4, ".values = c(\n", NIL);

  Node *c;
  int value = -1; // First number is zero
  for (c = firstChild(n); c; c = nextSibling(c)) {
    //      const char *tag = Char(nodeType(c));
    //      if (Strcmp(tag,"cdecl") == 0) {
    name = Getattr(c, "name");
    String *val = Getattr(c, "enumvalue");
    if(val && Char(val)) {
      int inval = (int) getNumber(val);
      if(inval == DEFAULT_NUMBER)
        value++;
      else
        value = inval;
    } else
      value++;

    Printf(scode, "%s%s%s'%s' = %d%s\n", tab8, tab8, tab8, name, value,
           nextSibling(c) ? ", " : "");
    //      }
  }

  Printv(scode, "))", NIL);
```

And `getNumber()` is:

```
static double getNumber(String *value) {
  double d = DEFAULT_NUMBER;
  if(Char(value)) {
    if(sscanf(Char(value), "%lf", &d) != 1)
      return(DEFAULT_NUMBER);
  }
  return(d);
}
```

And `DEFAULT_NUMBER` is:

```
static const double DEFAULT_NUMBER = `
```

So this fails to convert a hex constant (for you) because it uses `%lf` not `%i`, and then it fails to spot that the conversion failed, because it casts the returned value to `int` (so `.0000123456712312312323` -> `0`) and then that's not equal to `DEFAULT_NUMBER`.

But there are valid cases of constant expressions where `sscanf()` will fail, or will only parse the start of the value - here's a self-contained modified version of your testcase:

```
%inline %{
class testEnum {
    public:
        enum SHAPES {
            SQUARE,
            TRIANGLE,
            RECTANGLE
        };
        enum COLOURS {
            RED = 0x00FF0000,
            GREEN = 0x0000FF00,
            BLUE = 0x000000FF
        };
        enum NUMBERS {
            ONE = 1,
            TWO = ONE + ONE,
            THREE = (3),
            FIVE = 8 - THREE,
            SIX,
            SEVEN = 5 + 2,
            FOUR = ONE + 3,
            EIGHT = 010
        }
        testEnum(bool notEmpty) { }
};
%}
```

All the `NUMBERS` should have values matching their names, but for me with current git master, those map to the following in `enums.R`:

```
defineEnumeration('_testEnum__NUMBERS',
                    .values = c(
                        'ONE' = 1, 
                        'TWO' = 0, 
                        'THREE' = 0, 
                        'FIVE' = 8, 
                        'SIX' = 9, 
                        'SEVEN' = 5, 
                        'FOUR' = 0,
                        'EIGHT' = 10
))
```

Fundamentally, it's really hard to convert all enum initialisers to the target language, and I think the other target languages all have a mechanism which handles hard cases at runtime.

**Comment by ojwb** [comment]
@joequant PR #1118 improves things, but it just stuffs the C/C++ enum initialiser into the R code when it can't parse it which will sometimes work, but isn't a full solution.  I think someone with R knowledge needs to hook up a mechanism to get such enum values at runtime - I've taken this about as far as I can.

With that patch, the R output for my modified testcase above is:

```
defineEnumeration('_testEnum__NUMBERS',
                    .values = c(
                        'ONE' = 1, 
                        'TWO' = ONE+ONE, 
                        'THREE' = (3), 
                        'FIVE' = 8-THREE, 
                        'SIX' = 2, 
                        'SEVEN' = 5+2, 
                        'FOUR' = ONE+3, 
                        'EIGHT' = 8
))
```

So more values there are now correct, but at least `TWO`, `FIVE` and `FOUR` probably don't work as-is.  At least the failures should be noisy, rather than quietly using the wrong value as happens currently.

**Comment by davidcreasy** [comment]
Hi,
Thank you very much for looking at this so promptly, and your fix will certainly be good for me, although I do also have less important cases a little similar to your number example. A "noisy" failure is very helpful.

I guess the perl implementation works more cleanly because the value isn't in the .pm file, but is in the compiled code so it can rely on the C++ processor. For example, it produces a cxx file with:

    SV *sv = get_sv((char*) SWIG_prefix "testEnum_RED", TRUE | 0x2 | GV_ADDMULTI);
    sv_setsv(sv, SWIG_From_int  SWIG_PERL_CALL_ARGS_1(static_cast< int >(testEnum::RED)));
    SvREADONLY_on(sv);

Is a similar approach not possible for R? (Maybe I don't know enough R yet...)

Thanks,
David

**Comment by ojwb** [comment]
Yeah, that's what I mean by "hook up a mechanism to get such enum values at runtime".

But I basically know nothing useful about R.  I've assigned the ticket to joequant who hopefully can take a look at some point.

**Comment by joequant** [comment]
I merged in the patch since it does improve things.   Also since R doesn't see hex values, the full fix would be to have the parser see that its a hex and then output the integer for the hex.

**Comment by wsfulton** [comment]
The R test-suite breaks with this merge. When merging code, you ought to be looking at the generated output and comparing with the previous output to make sure it is okay. Running `make partial-r-test-suite` before and after and comparing the output for the entire test-suite is one way to do it. How can this be fixed asap as I'd like the Travis test-suite fully working again asap?

**Comment by joequant** [comment]
I'll fix this evening by turning some tests off.  It turns  out that the
tests that are now loudly breaking were generating incorrect code.

**Comment by joequant** [comment]
I made some changes to the r.cxx file to make it pass as many enums as I
could, and disabled the tests that are failing because
of the new change.

**Comment by wsfulton** [comment]
If I've understood this all correctly, the enum values are now initialized in R code instead of C code. If so, please put revert the patch and put it back to C code by default. This is the only fail-safe option. As far as I know all the languages do this by default. We made a real hash of trying to generate Python code for C++ argument default values instead of using C++ code. It still doesn't always work and one of the main goals of SWIG is to generate compilable code first and foremost over code that requires assumptions that may result in uncompilable code. A  feature to get the most user friendly and working code should then be made available. Java should be used as a model in this case, see http://swig.org/Doc3.0/Java.html#Java_enumerations, in particular note that enums values are set in C code and the `javaconst` and `%javaconstvalue` features are available to set them in Java code.

**Comment by ojwb** [comment]
I really wasn't intending the patch to get merged as it was...

> If I've understood this all correctly, the enum values are now initialized in R code instead of C code. If so, please put revert the patch and put it back to C code by default. This is the only fail-safe option.

Not quite - R was initialising them via R code before, but quietly using `0` in any case where the enum value didn't parse as a double (sic) with `sscanf()` (and then enum values following an incorrect `0` with no explicit value also got incorrect values, as it would increment from the incorrect `0`).

All my patch did was to (a) parse as an integer not a double and (b) fail noisily not quietly in cases where the value didn't parse.  The latter part was intended to show where the problem lay, and is why the patch wasn't suitable for merging.

I agree (and indeed said above) that in the general case enum values do need to come from C code at run time, but it's not a matter of restoring the code to do this for R, but rather of implementing such code.

**Comment by joequant** [comment]
The right thing to do is to initialize the enums in C code and then create
symbols which are accessible via R.  However, this will require some new
coding.  I'll look into doing this but volunteers are welcome.

The current patch is a stop gap so that the bad code that is generated
fails loudly rather than silently generating incorrect values.

**Comment by davidcreasy** [comment]
Happy to volunteer, but suspect that it would take me too long to get up to speed. My C/C++ coding is reasonable, but R knowledge is still limited, and I know almost nothing about SWIG internals. I can however commit to making some suggestions for additions to the R documentation section as it all becomes clearer to me over the next few weeks.

**Comment by richardbeare** [comment]
Hi,
I've come across this change as part of my work on refactoring as much as I can of the R module. The change breaks the SimpleITK wrapping procedure by generating illegal R code, as noted in some of the comments above. Specifically, we end up with R code like this:

```r
defineEnumeration('_itk__simple__PixelIDValueEnum',
                    .values = c(
                        'sitkUnknown' = -1, 
                        'sitkUInt8' = PixelIDToPixelIDValue<(BasicPixelID<(uint8_t)>)>::Result, 
                        'sitkInt8' = PixelIDToPixelIDValue<(BasicPixelID<(int8_t)>)>::Result, 
                        'sitkUInt16' = PixelIDToPixelIDValue<(BasicPixelID<(uint16_t)>)>::Result, 
                        'sitkInt16' = PixelIDToPixelIDValue<(BasicPixelID<(int16_t)>)>::Result, 
                        'sitkUInt32' = PixelIDToPixelIDValue<(BasicPixelID<(uint32_t)>)>::Result, 
))
```
which doesn't parse. The previous code generated all zeros, which was wrong, but parsed and thus allowed a custom set of values to be provided by the user.

I attacked this problem a number of years ago, but the PR never went through because I stuck to the conventions of the module at the time, in terms of name mangling etc, which were not in line with the rest of swig. For reference those PRs were #500 and #546.

There were several issues to address, which I'll return to now. I used the strategy mentioned by William above - a layer of C/C++ that could return the appropriate enum values, rather than have them
created in R code. As is clear from the discussion, and the simpleITK example, this is impossible or very, very hard.

Here's an explanation of why it is tricky with the current R strategy.

The R swig module uses special attributes assigned to functions to define return types and argument types. These get used when dispatching. Names stored in these attributes need to agree with the types created elsewhere in the bindings. i.e if an enumeration is used as an argument of a function the name of that enumeration gets recorded as an attribute of the function. The enumeration is passed in as a string and knowledge of the enumeration name is used to look up the correct underlying integer value in a special hidden environment.

Hidden environments are created and contents initialised by the "defineEnumeration" function. Currently those values are hardcoded in the swig generated call.

The steps we need to go through are

1. Create variables on the C/C++ side that can be wrapped and queried from the R code.

1. Modify defineEnumeration so that those variables are queried at an appropriate time. By appropriate time, I mean after the library containing the code to which swig is generating the binding has been loaded. Perhaps R "promises" can be used for this.

Most of the bits and pieces are in those previous PRs. I'll see about integrating them ASAP.

**Comment by richardbeare** [comment]
@wsfulton - have made a lot of progress, but struggling to find where the namespace feature is turned on for a particular language. An old email said that it wasn't enabled in R, but I'm struggling to uncover what is needed to enable it. Any pointers?

**Comment by ojwb** [comment]
Seems this was fixed by #1328 - generated R code is now:

```
defineEnumeration("_testEnum__SHAPES",
 .values=c("SQUARE" = .Call('R_swig_testEnum_SQUARE_get',FALSE, PACKAGE='enums'),
"TRIANGLE" = .Call('R_swig_testEnum_TRIANGLE_get',FALSE, PACKAGE='enums'),
"RECTANGLE" = .Call('R_swig_testEnum_RECTANGLE_get',FALSE, PACKAGE='enums')))

defineEnumeration("_testEnum__COLOURS",
 .values=c("RED" = .Call('R_swig_testEnum_RED_get',FALSE, PACKAGE='enums'),
"GREEN" = .Call('R_swig_testEnum_GREEN_get',FALSE, PACKAGE='enums'),
"BLUE" = .Call('R_swig_testEnum_BLUE_get',FALSE, PACKAGE='enums')))

defineEnumeration("_testEnum__NUMBERS",
 .values=c("ONE" = .Call('R_swig_testEnum_ONE_get',FALSE, PACKAGE='enums'),
"TWO" = .Call('R_swig_testEnum_TWO_get',FALSE, PACKAGE='enums'),
"THREE" = .Call('R_swig_testEnum_THREE_get',FALSE, PACKAGE='enums'),
"FIVE" = .Call('R_swig_testEnum_FIVE_get',FALSE, PACKAGE='enums'),
"SIX" = .Call('R_swig_testEnum_SIX_get',FALSE, PACKAGE='enums'),
"SEVEN" = .Call('R_swig_testEnum_SEVEN_get',FALSE, PACKAGE='enums'),
"FOUR" = .Call('R_swig_testEnum_FOUR_get',FALSE, PACKAGE='enums'),
"EIGHT" = .Call('R_swig_testEnum_EIGHT_get',FALSE, PACKAGE='enums')))
```
