### ISSUE TITLE
Error: autogen.sh make a illegal configure file

### ISSUE THREAD

**Issue by bio-punk** [swig/swig#1435]
Today, Install SWIG, use the way from "./Doc/Manual/Windows.html "
Building swig.exe on Windows by using Mingw and MSYS.
Step 1: install Mingw and MSYS by using MinGW Installer.
Step 2: install msys-automake, msys-autoconf and bison use MinGW Installer.
Step 3: add "C:\MinGW\msys\1.0" into path.
Step 4: using Git download SWIG.
Step 5: download the latest PCRE source tarball into "C:\MinGW\msys\1.0\src\swig".
Step 6: use "Tools/pcre-build.sh" build pcre
Step 7:  execute autogen.sh
After Step 7, I get a file named configure. In this file line 5850 and line 5968 is

```
if ac_fn_cxx_try_compile "$LINENO"; then :

        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }
    succeeded=yes
    found_system=yes

else # here is line 5850


fi
......
if ac_fn_cxx_try_compile "$LINENO"; then :

            { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }
        succeeded=yes
        found_system=yes

else # here is line 5968


fi
```

**Comment by vadz** [comment]
What is the problem exactly? I.e. everything looks good so far, why do you show these lines? Do you receive any errors for them? If so, which ones?

**Comment by bio-punk** [comment]
I means, there is nothing between 'fi' and 'else' . so,  the interpreter of MSYS-shell will tell me :

line 5850: syntax error near unexpected token `fi'

I have to delete line 5850 and line 5968 before execute configure, otherwise, shell will throw a error.

**Comment by vadz** [comment]
Hmm, indeed, I don't have these `else` lines in my autoconf output. What's your autoconf version? Mine is 2.69.

**Comment by ojwb** [comment]
@bio-punk "thumbs up emoji" is not an entirely helpful response - are you trying to say that change fixed things for you?

**Comment by bio-punk** [comment]
@ojwb oh, I mean it's maybe a right way to fix this bug.

**Comment by yennster** [comment]
I also have this issue when building SWIG on Windows, I fixed the issue in configure.sh by adding a colon after the else statement since it is empty:

Starting at line 5797:
```bash
if ac_fn_cxx_try_compile "$LINENO"; then :

        { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }
    succeeded=yes
    found_system=yes

else : #added a colon here


fi
```

Starting at line 5914:
```bash
_ACEOF
if ac_fn_cxx_try_compile "$LINENO"; then :

            { $as_echo "$as_me:${as_lineno-$LINENO}: result: yes" >&5
$as_echo "yes" >&6; }
        succeeded=yes
        found_system=yes

else : #added a colon here


fi
```

**Comment by ojwb** [comment]
OK, but we really don't want to start patching the generated configure script.

Removing the newline between `[` and `]` in `Tools/config/ax_boost_base.m4` seems like it would solve this, but that's maintained elsewhere so I'm hesitant to start applying local patches.  And the code is still like that upstream, which perhaps suggests there's something particular we're doing (though maybe we're just the only project using this macro and supporting building on Windows).  I don't see anything converting text files to `\r\n` line endings in the script for building SWIG on Windows, but this is rather outside my area of expertise.

@wsfulton Thoughts?

**Comment by wsfulton** [comment]
We ought just grab the latest from the autoconf archive. https://github.com/autoconf-archive/autoconf-archive/commits/master/m4/ax_boost_base.m4. My commit there in 2015 should be the version we have, so we ought to just try upgrading to their latest.

**Comment by ojwb** [comment]
I already checked the code in question is still present in the latest version of the macro, but maybe it's worth trying.  I can't test myself though as I don't have access to the platform in question.

**Comment by wsfulton** [comment]
Oh sorry, @ojwb, I misunderstood that you'd looked at the latest already.

I guess I better try and recreate this problem. @yennster, can you not try the fix mentioned above on 30 Jan?

**Comment by wsfulton** [comment]
I can't replicate this problem. Perhaps you weren't using the latest automake from msys (1.11)?? @bio-punk, do you still get this problem with the swig-4.0.0-beta1 release? If so, please re-open this issue.

**Comment by wsfulton** [comment]
@yennster, can you check too please?
