### ISSUE TITLE
Incorrect C++ Emitted For Template of Template with Enum Parameter

### ISSUE THREAD

**Issue by jrcalzada** [swig/swig#197]
Take the following declarations:

```
%include <std_vector.i>

enum class Foo
{
    a,
    b,
    c
};

template<Foo F>
class Bar
{   
};

%template(FooVector) std::vector<Bar<Foo::a>>;
```

This will generate code like the following:

``` c++
SWIGINTERN std::vector< Bar< enum Foo::a > >::const_reference std_vector_Sl_Bar_Sl_Foo_a_Sg__Sg__get(std::vector< Bar< Foo::a > > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
```

The return type is specified as `std::vector<Bar<enum Foo::a>>`. The `enum` keyword before the qualified enum member is invalid. The correct syntax is `std::vector<Bar<Foo::a>>`.

The issue seems to be in `SwigType_typedef_resolve` (typesys.c:650). In the process of fully qualifying types for the template, the qualified enum member is split into base and prefix. The prefix is then fully qualified on its own, yielding `enum Foo` and then joined together with the base, resulting in `enum Foo::a`.

Simple workaround would be to just strip `enum` from the fully qualified typename if if is an enum member that is being resolved. I've applied the following workaround locally and it seems to do the trick:

``` c++
rnameprefix = SwigType_typedef_resolve(nameprefix);
Replaceall(rnameprefix, "enum ", "");
```

**Comment by grigoryev-igor** [comment]
Good workaround, but wasn't complete for my case, which was more complex. 

To achieve complete result, I was forced to add
```
   Replaceall(tpr, "enum ", ""); 
   if(Equal(tp,tpr)) {tpr=0;} 

```
after line 563.

Piece of my code below. Previous workaround didn't work with wrapping count function of the set. Failed to strip excessive  enum keyword from fully qualified name for key_type;
```
template <class E, class T> struct TypedEnum {
    typedef T TargetType;
    typedef E EnumType;
    TypedEnum(): _value(E()) { }
    TypedEnum(E value) { _value = static_cast<T>(value); }
    operator E() const { return static_cast<E>(_value); }
private:
    T _value;
};


typedef enum {

    s = 1,

      c = 2,

    __first_unused_

} __sensor_status; 


typedef TypedEnum<__sensor_status, uchar> sensor_status; 

%{
#include <set>
%}

namespace std {

    template<class K> class set {
        public:
          typedef size_t size_type;
          typedef K key_type;
          typedef K value_type;
          typedef const value_type& const_reference;
          set();
          set(const set&);
          %rename(isEmpty) empty;
          bool empty() const;
          size_type size() const;
          void clear();

          void swap(set& v);


          size_type erase(const key_type& x);
          size_type count(const key_type& x) const;

    };

}

%template(SensorStatusSet) std::set< iris::uip::TypedEnum< __sensor_status,unsigned char > >;

```

**Comment by ojwb** [comment]
Still reproducible with current git master.

I had to adjust the supplied testcase to get code that compiled enough to show the error - here's my version:

```
%module test

%include <std_vector.i>

%inline %{
enum class Foo
{
    a,
    b,
    c
};

template<Foo F>
class Bar
{   
};
%}

%template(FooVector) std::vector<Bar<Foo::a>>;
```

**Comment by premont** [comment]
This is an old bug... but has it been fixed in a newer version?

**Comment by ojwb** [comment]
@premont I very much doubt it has been fixed since I last checked as that was only 3 months ago (2022-03-06) - see above.

**Comment by ojwb** [comment]
Still reproducible with current git master.

**Comment by ojwb** [comment]
Here's a complete (and simplified) testcase for the second example here:

```
%module y
%inline %{
template <class E, class T> struct TypedEnum {
    typedef T TargetType;
    typedef E EnumType;
    TypedEnum(): _value(E()) { }
    TypedEnum(E value) { _value = static_cast<T>(value); }
    operator E() const { return static_cast<E>(_value); }
private:
    T _value;
};

typedef enum { X } s;

typedef TypedEnum<s, int> sensor_status; 
%}

%include std_vector.i

%template(SensorStatusSet) std::vector< TypedEnum< s, int > >;
```

The problem here is that SWIG generates `enum s` but `s` is a `typedef` to an `enum`, not an `enum` itself, and GCC gives an error:

```
test2_wrap.cxx:4719:41: error: using typedef-name ‘s’ after ‘enum’
 4719 | SWIGINTERN std::vector< TypedEnum< enum s,int > >::size_type std_vector_Sl_TypedEnum_Sl_s_Sc_int_Sg__Sg____len__(std::vector< TypedEnum< s,int > > const *self){
      |                                         ^
```

**Comment by ojwb** [comment]
Both my reduced testcases above still fail with current git master (v4.2.0-73-g4dc621d8).

**Comment by ojwb** [comment]
https://sourceforge.net/p/swig/bugs/682/ looks like the same problem, or at least closely related.

For that I managed to come up with a much simpler reproducer which just needs a function call with a `const` reference parameter:

```
%module x
%inline %{
typedef enum { BAZ1 } baz;
void enumbugexample( baz const & ) { }
%}
```

Then:

```
$ swig -c++ -python simplified.i
$ grep 'enum baz' simplified_wrap.cxx
  enumbugexample((enum baz const &)*arg1);
static swig_type_info _swigt__p_baz = {"_p_baz", "baz *|enum baz *", 0, 0, (void*)0, 0};
```

The `const &` seems to be needed.

I notice the type info entry includes `enum baz *` which seems wrong too.

**Comment by ojwb** [comment]
There seem to be two distinct bugs discussed here.

The original report is for a C++11 `enum class`, and we currently incorrectly include `enum ` when qualifying an enumerator name.  I have a patch which seems to fix this.

The second example here and the linked SF bug both create a typedef to a "traditional" C++ `enum`, and SWIG incorrectly includes `enum ` plus the typedef name - it needs to use the typedef name alone (it could instead use `enum ` plus the enum name if the enum isn't anonymous, but it is anonymous in both cases here).
